services:
  api:
    build:
      context: ./inventoryapi
      dockerfile: Dockerfile
    container_name: "api"
    ports:
      - '8080:8080'
  ui:
    build:
      context: ./ts-inventory-ui
      dockerfile: Dockerfile
    container_name: "ui"
    ports:
      - "5173:5173"
    volumes:
      - ./ts-inventory-ui:/app
      - /app/node_modules
